# Generated by Django 6.0.5 on 2026-06-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('artist', 'Artiste'), ('host', 'Hôte')], default='host', max_length=10),
        ),
    ]
