# Generated by Django 6.0.5 on 2026-06-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='category',
            field=models.CharField(choices=[('class', 'Atelier'), ('event', 'Événement'), ('commission', 'Commission'), ('performance', 'Spectacle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='offering',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Prix fixe'), ('hourly', 'Par heure'), ('free', 'Gratuit'), ('contact', 'Sur devis')], default='fixed', max_length=10),
        ),
    ]
