# Generated by Django 6.0.5 on 2026-06-03 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0002_alter_offering_category_alter_offering_price_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Décrivez votre espace, la date souhaitée, le nombre de participants…')),
                ('date_wish', models.DateField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('guests', models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de participants')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('declined', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=12)),
                ('artist_note', models.TextField(blank=True, verbose_name="Réponse de l'artiste")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_host', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='offerings.offering')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
